/*~***************************************
 * Auto generated by start.spring.io
 * Utilizing Java 1.8, Spring, Gradle, for REST
 *~**************************************/
package com.example.kenzancodeproject;

import com.example.kenzancodeproject.model.Employee;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

import java.io.IOException;

@SpringBootApplication
public class KenzancodeprojectApplication {

	public static void main(String[] args) {
		SpringApplication.run(KenzancodeprojectApplication.class, args);
	}
}
